services:
  web:
    image: crpi-qf67s2qzcbuiic6v.cn-hangzhou.personal.cr.aliyuncs.com/moguangkeji/mg_test:v0.0.2
    build: . # 可选，如果你想重新构建本地镜像就保留
    ports:
      - "7001:7001"
    env_file:
      - .env
    networks:
      - agent-demo2_default
    command: >
      sh -c "./wait-for-it.sh db:5432 -- 
            alembic upgrade head &&
            gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:7001"

networks:
  agent-demo2_default:
    external: true
