services:
  mg_agent:
    image: crpi-qf67s2qzcbuiic6v.cn-hangzhou.personal.cr.aliyuncs.com/moguangkeji/mg_agent:v0.0.5
    container_name: mg-main
    ports:
      - "1234:80"
    env_file:
      - .env
    networks:
      - backend
    restart: unless-stopped
    command: >
      sh -c "
        alembic upgrade head &&
        gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:80
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend:
    name: mg_backend
    external: true
