"""first

Revision ID: ec6e5ded33d2
Revises: 
Create Date: 2025-04-20 14:47:14.676894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6e5ded33d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名(唯一)'),
    sa.Column('userid', sa.String(length=64), nullable=False, comment='用户唯一标识（UUID）'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱地址(可选)'),
    sa.Column('hashed_password', sa.String(length=128), nullable=False, comment='加密密码(必填)'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='账号是否激活'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间(自动设置)'),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=True, comment='用户角色(默认普通用户)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_userid'), 'users', ['userid'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_record',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键 ID'),
    sa.Column('user_id', sa.String(length=64), nullable=True, comment='关联的用户唯一标识（UUID）'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='前端传递的消息唯一标识'),
    sa.Column('role', sa.String(length=32), nullable=False, comment='消息角色，如 user / assistant'),
    sa.Column('model', sa.String(length=128), nullable=True, comment='使用的大模型名称'),
    sa.Column('response_start_time', sa.DateTime(), nullable=True, comment='回复开始时间'),
    sa.Column('response_end_time', sa.DateTime(), nullable=True, comment='回复结束时间'),
    sa.Column('text', sa.String(), nullable=True, comment='文本内容'),
    sa.Column('image', sa.JSON(), nullable=True, comment='图片列表，字符串数组'),
    sa.Column('video', sa.String(), nullable=True, comment='视频链接'),
    sa.ForeignKeyConstraint(['user_id'], ['users.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_record_id'), 'chat_record', ['id'], unique=False)
    op.create_index(op.f('ix_chat_record_user_id'), 'chat_record', ['user_id'], unique=False)
    op.create_index(op.f('ix_chat_record_uuid'), 'chat_record', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_record_uuid'), table_name='chat_record')
    op.drop_index(op.f('ix_chat_record_user_id'), table_name='chat_record')
    op.drop_index(op.f('ix_chat_record_id'), table_name='chat_record')
    op.drop_table('chat_record')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_userid'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
